### ISSUE TITLE
`pip install pyconcrete`command failed, failed building wheel for pyconcrete

### ISSUE THREAD

**Issue by Guoozz** [Falldog/pyconcrete#33]
![image](https://user-images.githubusercontent.com/8208557/39686931-8b2c32d6-51fe-11e8-856e-cc676f12a829.png)

my environment: `Vagrant`:
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-6.7"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision "shell", path: "bootstrap.sh"
end
``
`bootstrap`:
```bash
#!/usr/bin/env bash

python_path=/usr/local

yum -y update && \
    yum groupinstall -y development && \
    yum install -y \
    bzip2-devel \
    git \
    hostname \
    openssl \
    openssl-devel \
    sqlite-devel \
    sudo \
    tar \
    wget \
    zlib-devel \
    mysql-devel \
    libaio \
    libvirt-devel \
    which \
    python-devel \
    readline-devel \
    gdbm-devel \
    ncurses-libs

cd /tmp
wget https://www.python.org/ftp/python/2.7.6/Python-2.7.6.tgz
tar xvfz Python-2.7.6.tgz
cd Python-2.7.6
./configure --prefix=$python_path
make
make install
```

**Comment by Falldog** [comment]
@Guoozz I can't see the steps about `pyconcrete`, only the way to build python from source

**Comment by k870611** [comment]
I face same problem too, my OS is centos 7.2, Python 3.6.5 |Anaconda, Inc. And I hava update setuptools to  40.6.3, wheel to 0.32.3, pip to 18.1, but it stiil show the error msg below

 [root@localhost tool]# python -m pip install pyconcrete-0.12.1.tar.gz
Processing ./pyconcrete-0.12.1.tar.gz
Building wheels for collected packages: pyconcrete
  Running setup.py bdist_wheel for pyconcrete ... error
  Complete output from command /home/anaconda3/bin/python -u -c "import setuptoo                ls, tokenize;__file__='/tmp/pip-req-build-d9t_g5fy/setup.py';f=getattr(tokenize,                 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(comp                ile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-u_ks8h_2 --python-ta                g cp36:
  running bdist_wheel
  running build
  please input the passphrase
  for encrypt your python script (enter for default) :
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-d9t_g5fy/setup.py", line 416, in <module>
      distclass=ExeDistribution,
    File "/home/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_com                mands
      self.run_command(cmd)
    File "/home/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_com                mand
      cmd_obj.run()
    File "/home/anaconda3/lib/python3.6/site-packages/wheel/bdist_wheel.py", lin                e 188, in run
      self.run_command('build')
    File "/home/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_comm                and
      self.distribution.run_command(command)
    File "/home/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_com                mand
      cmd_obj.run()
    File "/tmp/pip-req-build-d9t_g5fy/setup.py", line 167, in run
      self.pre_process()
    File "/tmp/pip-req-build-d9t_g5fy/setup.py", line 140, in pre_process
      self.passphrase = input("please input the passphrase \nfor encrypt your py                thon script (enter for default) : \n")
  EOFError: EOF when reading a line

  ----------------------------------------
  Failed building wheel for pyconcrete
  Running setup.py clean for pyconcrete
Failed to build pyconcrete
Installing collected packages: pyconcrete
  Running setup.py install for pyconcrete ... error
    Complete output from command /home/anaconda3/bin/python -u -c "import setupt                ools, tokenize;__file__='/tmp/pip-req-build-d9t_g5fy/setup.py';f=getattr(tokeniz                e, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(co                mpile(code, __file__, 'exec'))" install --record /tmp/pip-record-lcc9sxv3/instal                l-record.txt --single-version-externally-managed --compile:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: option --single-version-externally-managed not recognized

    ----------------------------------------
Command "/home/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__=                '/tmp/pip-req-build-d9t_g5fy/setup.py';f=getattr(tokenize, 'open', open)(__file_                _);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'e                xec'))" install --record /tmp/pip-record-lcc9sxv3/install-record.txt --single-ve                rsion-externally-managed --compile" failed with error code 1 in /tmp/pip-req-bui                ld-d9t_g5fy/

Does have other way to solve this error ? The Info I search is said update setuptools and wheel can solve this problem.

Thanks

**Comment by zoakes** [comment]
I have this same issue, did anyone figure this out?

**Comment by tompap** [comment]
Same here :/

**Comment by javadba** [comment]
likewise

**Comment by pfee** [comment]
Same with openSUSE Leap 15.1, python 3.6.9, python3-pip-10.0.1-lp151.2.2.noarch

Some of the error message:
=======
please input the passphrase
  for encrypt your python script (enter for default) :
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
<snip ...>
    File "/tmp/pip-install-kzk6i9r5/pyconcrete/setup.py", line 140, in pre_process
      self.passphrase = input("please input the passphrase \nfor encrypt your python script (enter for default) : \n")
  EOFError: EOF when reading a line
  
  ----------------------------------------
  Failed building wheel for pyconcrete

**Comment by pfee** [comment]
Looking around elsewhere for mentions of pip install and stdin, it appears that pip used to allow user interaction while setup.py was running.  However this is no longer the case and pip closes stdin, preventing setup.py reading.

[PIP issue #2732](https://github.com/pypa/pip/issues/2732)

This seems like the reason why the "input()" call in setup.py is failing.  Hence the fix may be to make pyconcrete's setup.py non-interactive.

**Comment by pfee** [comment]
Potential way to pass the passphase into setup.py without needing input from the terminal:

https://stackoverflow.com/questions/18725137/how-to-obtain-arguments-passed-to-setup-py-from-pip-with-install-option

https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-install-option

**Comment by Falldog** [comment]
It should be fix in #92
