### ISSUE TITLE
__spec__ is None error

### ISSUE THREAD

**Issue by blackboxx** [Falldog/pyconcrete#44]
Hello dear developer. I've just used an django example, you've provided and it works!
But when i try to run my own django project (after it was encrypted) 
I run this to encrypt, command gives encrypted result, 
`python ../pyconcrete-master/pyconcrete-admin.py compile --source=/Users/bbx/envs/liga-basic/liga-basic-build --pye --remove-py --remove-pyc  -i backend/wsgi.py manage` 

but after i run a server with **python manage runserver** I get an error:
`Traceback (most recent call last):
  File "/Users/bbx/.pyenv/versions/mypyenv/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/bbx/.pyenv/versions/mypyenv/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/Users/bbx/.pyenv/versions/mypyenv/lib/python3.5/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/Users/bbx/.pyenv/versions/mypyenv/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/bbx/.pyenv/versions/mypyenv/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/bbx/.pyenv/versions/mypyenv/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/bbx/.pyenv/versions/mypyenv/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/bbx/.pyenv/versions/mypyenv/lib/python3.5/site-packages/django/apps/config.py", line 197, in import_models
    if module_has_submodule(self.module, MODELS_MODULE_NAME):
  File "/Users/bbx/.pyenv/versions/mypyenv/lib/python3.5/site-packages/django/utils/module_loading.py", line 79, in module_has_submodule
    return importlib_find(full_module_name, package_path) is not None
  File "/Users/bbx/.pyenv/versions/3.5.5/lib/python3.5/importlib/util.py", line 102, in find_spec
    raise ValueError('{}.__spec__ is None'.format(name))
ValueError: apps.pages.models.__spec__ is None
`
Is that is a problem of your package or my app?

**Comment by blackboxx** [comment]
by the way, I used pipenv, because on a mac, there was a problem with ld, during installation

**Comment by blackboxx** [comment]
Python version 3.5

**Comment by blackboxx** [comment]
Same problem with python 3.3.0 and 3.4.0

**Comment by Falldog** [comment]
@blackboxx How you install pyconcrete? By pipenv or pip?
By the exception call stack I can't see any code related with pyconcrete.

**Comment by blackboxx** [comment]
With regular virtualenv it is not working for me at all. So i found a way to execute this project. I'm on a osX 10.12.

1) Create a new pyenv
env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv virtualenv 3.4.0 mypyenv
2) Activate it
pyenv activate mypyenv
install it like this: 
(nameofenv) ~/envs/folder/pyconcrete-master$  python setup.py install


Than it gives many log like normal install  but ends with some diagnostics error:

"""
src/pyconcrete_ext/openaes/src/oaes_lib.c:253:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
        /*c*/   0xec, 0xe2, 0xf0, 0xfe, 0xd4, 0xda, 0xc8, 0xc6, 0x9c, 0x92, 0x80, 0x8e, 0xa4, 0xaa, 0xb8, 0xb6,
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                {                                                                                             }
src/pyconcrete_ext/openaes/src/oaes_lib.c:254:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
        /*d*/   0x0c, 0x02, 0x10, 0x1e, 0x34, 0x3a, 0x28, 0x26, 0x7c, 0x72, 0x60, 0x6e, 0x44, 0x4a, 0x58, 0x56,
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                {                                                                                             }
src/pyconcrete_ext/openaes/src/oaes_lib.c:255:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
        /*e*/   0x37, 0x39, 0x2b, 0x25, 0x0f, 0x01, 0x13, 0x1d, 0x47, 0x49, 0x5b, 0x55, 0x7f, 0x71, 0x63, 0x6d,
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                {                                                                                             }
src/pyconcrete_ext/openaes/src/oaes_lib.c:256:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
        /*f*/   0xd7, 0xd9, 0xcb, 0xc5, 0xef, 0xe1, 0xf3, 0xfd, 0xa7, 0xa9, 0xbb, 0xb5, 0x9f, 0x91, 0x83, 0x8d,
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                {                                                                                             }
src/pyconcrete_ext/openaes/src/oaes_lib.c:475:3: warning: implicitly declaring library function 'sprintf' with type
      'int (char *, const char *, ...)' [-Wimplicit-function-declaration]
                sprintf( _temp, "%02x ", data[_i] );
                ^
src/pyconcrete_ext/openaes/src/oaes_lib.c:475:3: note: include the header <stdio.h> or explicitly provide a declaration for
      'sprintf'
src/pyconcrete_ext/openaes/src/oaes_lib.c:515:43: warning: implicit declaration of function 'getpid' is invalid in C99
      [-Wimplicit-function-declaration]
                        (uint32_t) ( _test + timer.millitm ) + getpid();
                                                               ^
src/pyconcrete_ext/openaes/src/oaes_lib.c:515:43: warning: this function declaration is not a prototype [-Wstrict-prototypes]
src/pyconcrete_ext/openaes/src/oaes_lib.c:30:19: warning: unused variable '_NR' [-Wunused-const-variable]
static const char _NR[] = {
                  ^
src/pyconcrete_ext/openaes/src/oaes_lib.c:291:17: warning: unused function 'oaes_word_rot_right' [-Wunused-function]
static OAES_RET oaes_word_rot_right( uint8_t word[OAES_COL_LEN] )
                ^
134 warnings generated.
clang -arch x86_64 build/temp.macosx-10.12-x86_64-3.4/src/pyconcrete_exe/pyconcrete_exe.o build/temp.macosx-10.12-x86_64-3.4/src/pyconcrete_ext/pyconcrete.o build/temp.macosx-10.12-x86_64-3.4/src/pyconcrete_ext/openaes/src/oaes_base64.o build/temp.macosx-10.12-x86_64-3.4/src/pyconcrete_ext/openaes/src/oaes_lib.o -lpython3.4m -o build/scripts-3.4/pyconcrete
ld: library not found for -lpython3.4m
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'clang' failed with exit status 1
"""
then if i run python
>>> import pyconcrete 
its works.

**Comment by blackboxx** [comment]
But with python 3.5.5 installation ends without any fails

**Comment by blackboxx** [comment]
now I confirm that with new 2.0 django insallation it works nice with 3.5.5 and new django app is going to be ok. So it seems that it is some kind of user-app problem (my app/ my problem) or it is other problem

**Comment by Falldog** [comment]
I had not tried on Mac to install pyconcrete.
Look at the error messages
```
clang -arch x86_64 build/temp.macosx-10.12-x86_64-3.4/src/pyconcrete_exe/pyconcrete_exe.o build/temp.macosx-10.12-x86_64-3.4/src/pyconcrete_ext/pyconcrete.o build/temp.macosx-10.12-x86_64-3.4/src/pyconcrete_ext/openaes/src/oaes_base64.o build/temp.macosx-10.12-x86_64-3.4/src/pyconcrete_ext/openaes/src/oaes_lib.o -lpython3.4m -o build/scripts-3.4/pyconcrete
ld: library not found for -lpython3.4m
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'clang' failed with exit status 1
```

It's maybe pyconcrete issue, linker flags seem wrong
