### ISSUE TITLE
ImportError: /lib64/tls/libc.so.6: version `GLIBC_2.14' not found 

### ISSUE THREAD

**Issue by chi2liu** [Falldog/pyconcrete#49]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/liuchi02/.jumbo/lib/python2.7/site-packages/pyconcrete/__init__.py", line 29, in <module>
    from . import _pyconcrete
ImportError: /lib64/tls/libc.so.6: version `GLIBC_2.14' not found (required by /home/liuchi02/.jumbo/lib/python2.7/site-packages/pyconcrete/_pyconcrete.so)

**Comment by Falldog** [comment]
Do you build & run pyconcrete on the same machine?
