### ISSUE TITLE
multithreading Support

### ISSUE THREAD

**Issue by MyraBaba** [Falldog/pyconcrete#60]
Hi,

I have strange errors . :Is pyconcrete support multithreading python ?

ie : 

i am imported 👍 

import sqlite3 as lite

but it gives . 

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "_mqt_production-RemoteCamMultidb.py", line 745, in update_data_sql_deamon
    conn = lite.connect("personelDBv2")
NameError: name 'lite' is not defined

**Comment by Falldog** [comment]
duplicate issue #53

**Comment by Falldog** [comment]
Please try the latest code
