### ISSUE TITLE
pyconcrete test error ?

### ISSUE THREAD

**Issue by jekoie** [Falldog/pyconcrete#67]
### After install pyconcrete and run test, it show errors?
```
./pyconcrete-admin.py test
'C:\Users\jett' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
E'C:\Users\jett' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
E'C:\Users\jett' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
E'C:\Users\jett' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
E'C:\Users\jett' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
E'C:\Users\jett' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
E'C:\Users\jett' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
E
======================================================================
ERROR: setUpClass (test_admin.TestAdminIgnoreFilesScript)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\jett chen\Desktop\tmp\pyconcrete\test\base.py", line 147, in setUpClass
    build_tmp_pyconcrete(cls.passphrase)
  File "C:\Users\jett chen\Desktop\tmp\pyconcrete\test\base.py", line 86, in build_tmp_pyconcrete
    subprocess.check_call(' '.join(cmd), shell=True)
  File "C:\Users\jett chen\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Users\jett chen\AppData\Local\Programs\Python\Python37\python.exe setup.py install --passphrase=Falldog --install-base=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_rklbxgbz --install-purelib=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_rklbxgbz --install-platlib=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_rklbxgbz --install-scripts=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_rklbxgbz\scripts --install-headers=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_rklbxgbz\headers --install-data=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_rklbxgbz\data --quiet' returned non-zero exit status 1.

======================================================================
ERROR: setUpClass (test_admin.TestAdminScript)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\jett chen\Desktop\tmp\pyconcrete\test\base.py", line 147, in setUpClass
    build_tmp_pyconcrete(cls.passphrase)
  File "C:\Users\jett chen\Desktop\tmp\pyconcrete\test\base.py", line 86, in build_tmp_pyconcrete
    subprocess.check_call(' '.join(cmd), shell=True)
  File "C:\Users\jett chen\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Users\jett chen\AppData\Local\Programs\Python\Python37\python.exe setup.py install --passphrase=Falldog --install-base=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_a0sraibt --install-purelib=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_a0sraibt --install-platlib=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_a0sraibt --install-scripts=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_a0sraibt\scripts --install-headers=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_a0sraibt\headers --install-data=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_a0sraibt\data --quiet' returned non-zero exit status 1.

======================================================================
ERROR: setUpClass (test_basic.TestBasic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\jett chen\Desktop\tmp\pyconcrete\test\base.py", line 147, in setUpClass
    build_tmp_pyconcrete(cls.passphrase)
  File "C:\Users\jett chen\Desktop\tmp\pyconcrete\test\base.py", line 86, in build_tmp_pyconcrete
    subprocess.check_call(' '.join(cmd), shell=True)
  File "C:\Users\jett chen\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Users\jett chen\AppData\Local\Programs\Python\Python37\python.exe setup.py install --passphrase=Falldog --install-base=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_0fp036b4 --install-purelib=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_0fp036b4 --install-platlib=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_0fp036b4 --install-scripts=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_0fp036b4\scripts --install-headers=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_0fp036b4\headers --install-data=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_0fp036b4\data --quiet' returned non-zero exit status 1.

======================================================================
ERROR: setUpClass (test_concrete.TestConcrete)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\jett chen\Desktop\tmp\pyconcrete\test\base.py", line 147, in setUpClass
    build_tmp_pyconcrete(cls.passphrase)
  File "C:\Users\jett chen\Desktop\tmp\pyconcrete\test\base.py", line 86, in build_tmp_pyconcrete
    subprocess.check_call(' '.join(cmd), shell=True)
  File "C:\Users\jett chen\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Users\jett chen\AppData\Local\Programs\Python\Python37\python.exe setup.py install --passphrase=Falldog --install-base=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_qcdk85gt --install-purelib=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_qcdk85gt --install-platlib=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_qcdk85gt --install-scripts=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_qcdk85gt\scripts --install-headers=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_qcdk85gt\headers --install-data=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_qcdk85gt\data --quiet' returned non-zero exit status 1.

======================================================================
ERROR: setUpClass (test_exe.TestPyconcreteExe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\jett chen\Desktop\tmp\pyconcrete\test\base.py", line 147, in setUpClass
    build_tmp_pyconcrete(cls.passphrase)
  File "C:\Users\jett chen\Desktop\tmp\pyconcrete\test\base.py", line 86, in build_tmp_pyconcrete
    subprocess.check_call(' '.join(cmd), shell=True)
  File "C:\Users\jett chen\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Users\jett chen\AppData\Local\Programs\Python\Python37\python.exe setup.py install --passphrase=Falldog --install-base=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_yucmhwsv --install-purelib=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_yucmhwsv --install-platlib=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_yucmhwsv --install-scripts=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_yucmhwsv\scripts --install-headers=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_yucmhwsv\headers --install-data=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_yucmhwsv\data --quiet' returned non-zero exit status 1.

======================================================================
ERROR: setUpClass (test_import_hook.TestImportHook)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\jett chen\Desktop\tmp\pyconcrete\test\base.py", line 147, in setUpClass
    build_tmp_pyconcrete(cls.passphrase)
  File "C:\Users\jett chen\Desktop\tmp\pyconcrete\test\base.py", line 86, in build_tmp_pyconcrete
    subprocess.check_call(' '.join(cmd), shell=True)
  File "C:\Users\jett chen\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Users\jett chen\AppData\Local\Programs\Python\Python37\python.exe setup.py install --passphrase=Falldog --install-base=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_sn4df9if --install-purelib=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_sn4df9if --install-platlib=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_sn4df9if --install-scripts=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_sn4df9if\scripts --install-headers=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_sn4df9if\headers --install-data=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_sn4df9if\data --quiet' returned non-zero exit status 1.

======================================================================
ERROR: setUpClass (test_pye_performance.TestPerformance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\jett chen\Desktop\tmp\pyconcrete\test\base.py", line 147, in setUpClass
    build_tmp_pyconcrete(cls.passphrase)
  File "C:\Users\jett chen\Desktop\tmp\pyconcrete\test\base.py", line 86, in build_tmp_pyconcrete
    subprocess.check_call(' '.join(cmd), shell=True)
  File "C:\Users\jett chen\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Users\jett chen\AppData\Local\Programs\Python\Python37\python.exe setup.py install --passphrase=Falldog --install-base=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_o8ir7x3x --install-purelib=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_o8ir7x3x --install-platlib=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_o8ir7x3x --install-scripts=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_o8ir7x3x\scripts --install-headers=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_o8ir7x3x\headers --install-data=C:\Users\JETTCH~1\AppData\Local\Temp\pyconcrete_lib_o8ir7x3x\data --quiet' returned non-zero exit status 1.

----------------------------------------------------------------------
Ran 0 tests in 0.317s

FAILED (errors=7)

jett chen@jett MINGW64 ~/Desktop/tmp/pyconcrete (master)
```

**Comment by Falldog** [comment]
I'm not sure pyconcrete work normally under MINGW64. You should read python extension document first. pyconcrete need build pyconcrete.so from C source code.

reference:
https://matthew-brett.github.io/pydagogue/python_msvc.html https://github.com/cython/cython/wiki/CythonExtensionsOnWindows
