### ISSUE TITLE
Installation Error in Kali Linux ( on python 3.8)

### ISSUE THREAD

**Issue by alimp5** [Falldog/pyconcrete#78]
OS: Debian (Kali Linux)
Python Ver:  3.8.6  - 64 bit
How to fix it?

```
root@milani:~# pip install pyconcrete --egg --install-option="--passphrase=456789"
Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --egg
```

```

root@milani:~# pip3 install pyconcrete
Collecting pyconcrete
  Using cached pyconcrete-0.12.1.tar.gz (46 kB)
Building wheels for collected packages: pyconcrete
  Building wheel for pyconcrete (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-237u2fow/pyconcrete/setup.py'"'"'; __file__='"'"'/tmp/pip-install-237u2fow/pyconcrete/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-iiwz994w
       cwd: /tmp/pip-install-237u2fow/pyconcrete/
  Complete output (27 lines):
  /tmp/pip-install-237u2fow/pyconcrete/setup.py:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp
  running bdist_wheel
  running build
  please input the passphrase
  for encrypt your python script (enter for default) :
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-237u2fow/pyconcrete/setup.py", line 371, in <module>
      setup(
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-237u2fow/pyconcrete/setup.py", line 167, in run
      self.pre_process()
    File "/tmp/pip-install-237u2fow/pyconcrete/setup.py", line 140, in pre_process
      self.passphrase = input("please input the passphrase \nfor encrypt your python script (enter for default) : \n")
  EOFError: EOF when reading a line
  ----------------------------------------
  ERROR: Failed building wheel for pyconcrete
  Running setup.py clean for pyconcrete
Failed to build pyconcrete
Installing collected packages: pyconcrete
    Running setup.py install for pyconcrete ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-237u2fow/pyconcrete/setup.py'"'"'; __file__='"'"'/tmp/pip-install-237u2fow/pyconcrete/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6_bezeu5/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/pyconcrete
         cwd: /tmp/pip-install-237u2fow/pyconcrete/
    Complete output (8 lines):
    /tmp/pip-install-237u2fow/pyconcrete/setup.py:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
      import imp
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help
    
    error: option --single-version-externally-managed not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-237u2fow/pyconcrete/setup.py'"'"'; __file__='"'"'/tmp/pip-install-237u2fow/pyconcrete/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6_bezeu5/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/pyconcrete Check the logs for full command output.
```

**Comment by Falldog** [comment]
pyconcrete may not available on latest pip
please install by setup.py directly
